# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "release" ]


permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
  
    - name: Move To BE dir
      run: cd BE/
  
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    ## gradle caching
    - name: Gradle Caching
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    ## create application-prod1.properties
    - name: make application-prod1.properties
      if: contains(github.ref, 'release') # branch가 main 일 때, 나머지는 위와 동일
      run: |
          cd ./src/main/resources
          touch ./application-mysql-db.yml
          echo "${{ secrets.PROPERTIES_MYSQL_DB }}" > ./application-mysql-db.yml
      shell: bash

    ## gradle build
    - name: Build with Gradle
      run: ./gradlew build -x test

    ## docker build & push to production
    - name: Docker build & push to prod1
      if: contains(github.ref, 'release')
      run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile-prod1 -t ${{ secrets.DOCKER_REPO }}/codesquad-airbnb-team21-prod1 .
          docker push ${{ secrets.DOCKER_REPO }}/codesquad-airbnb-team21-prod1
          
    ## deploy to production
    - name: Deploy to prod
      uses: appleboy/ssh-action@master
      id: deploy-prod
      if: contains(github.ref, 'release')
      with:
          host: ${{ secrets.HOST_PROD1 }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
              sudo docker rm -f $(docker ps -qa)
              sudo docker pull ${{ secrets.DOCKER_REPO }}/codesquad-airbnb-team21-prod1
              docker-compose up -d
              docker image prune -f
